"""delete unique name

Revision ID: 350b864ded41
Revises: 2d43b29fbf49
Create Date: 2022-11-18 18:41:10.127224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350b864ded41'
down_revision = '2d43b29fbf49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
