"""modify image column data type

Revision ID: c00411c5edf6
Revises: 06b8bb7717f5
Create Date: 2022-11-20 17:36:44.591235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00411c5edf6'
down_revision = '06b8bb7717f5'
branch_labels = None
depends_on = None


def upgrade() :
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Column('Image', sa.String(), nullable=True)
    # ### end Alembic commands ###


def downgrade() :
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
